#!/bin/bash
# Simple script to process all of the images inside the inputs/ folder
# We will be running this script inside the visionai/clouddream Docker image
# Copyright vision.ai, 2015

function run_me {
    echo $1
    layer=$1
    suffix=`echo $layer|sed -e "s/\/_/g"`               #replace any slash with underscore or filename will be messed up!
    echo DEBUG layer is $layer file suffix will be $suffix 
    ./create_settings.sh "300" "0.5" "27" "$layer"
    ./process_custom_images_once.sh "_$suffix"
    sleep 1
}
while [ true ];
do
    run_me "conv1/7x7_s2"
	run_me "pool1/3x3_s2"
	run_me "pool1/norm1"
	run_me "conv2/3x3_reduce"
	run_me "conv2/3x3"
	run_me "conv2/norm2"
	run_me "pool2/3x3_s2"
	run_me "inception_3a/1x1"
	run_me "inception_3a/3x3_reduce"
	run_me "inception_3a/3x3"
	run_me "inception_3a/5x5_reduce"
	run_me "inception_3a/5x5"
	run_me "inception_3a/pool"
	run_me "inception_3a/pool_proj"
	run_me "inception_3a/output"
	run_me "inception_3b/1x1"
	run_me "inception_3b/3x3_reduce"
	run_me "inception_3b/3x3"
	run_me "inception_3b/5x5_reduce"
	run_me "inception_3b/5x5"
	run_me "inception_3b/pool"
	run_me "inception_3b/pool_proj"
	run_me "inception_3b/output"
	run_me "pool3/3x3_s2"
	run_me "inception_4a/1x1"
	run_me "inception_4a/3x3_reduce"
	run_me "inception_4a/3x3"
	run_me "inception_4a/5x5_reduce"
	run_me "inception_4a/5x5"
	run_me "inception_4a/pool"
	run_me "inception_4a/pool_proj"
	run_me "inception_4a/output"
	run_me "inception_4b/1x1"
	run_me "inception_4b/3x3_reduce"
	run_me "inception_4b/3x3"
	run_me "inception_4b/5x5_reduce"
	run_me "inception_4b/5x5"
	run_me "inception_4b/pool"
	run_me "inception_4b/pool_proj"
	run_me "inception_4b/output"
	run_me "inception_4c/1x1"
	run_me "inception_4c/3x3_reduce"
	run_me "inception_4c/3x3"
	run_me "inception_4c/5x5_reduce"
	run_me "inception_4c/5x5"
	run_me "inception_4c/pool"
	run_me "inception_4c/pool_proj"
	run_me "inception_4c/output"
	run_me "inception_4d/1x1"
	run_me "inception_4d/3x3_reduce"
	run_me "inception_4d/3x3"
	run_me "inception_4d/5x5_reduce"
	run_me "inception_4d/5x5"
	run_me "inception_4d/pool"
	run_me "inception_4d/pool_proj"
	run_me "inception_4d/output"
	run_me "inception_4e/1x1"
	run_me "inception_4e/3x3_reduce"
	run_me "inception_4e/3x3"
	run_me "inception_4e/5x5_reduce"
	run_me "inception_4e/5x5"
	run_me "inception_4e/pool"
	run_me "inception_4e/pool_proj"
	run_me "inception_4e/output"
	run_me "pool4/3x3_s2"
	run_me "inception_5a/1x1"
	run_me "inception_5a/3x3_reduce"
	run_me "inception_5a/3x3"
	run_me "inception_5a/5x5_reduce"
	run_me "inception_5a/5x5"
	run_me "inception_5a/pool"
	run_me "inception_5a/pool_proj"
	run_me "inception_5a/output"
	run_me "inception_5b/1x1"
	run_me "inception_5b/3x3_reduce"
	run_me "inception_5b/3x3"
	run_me "inception_5b/5x5_reduce"
	run_me "inception_5b/5x5"
	run_me "inception_5b/pool"
	run_me "inception_5b/pool_proj"
	run_me "inception_5b/output"
    sleep 1    
done